name = "bikeraworker"
main = "worker.js"
compatibility_date = "2024-01-01"

# Account ID
account_id = "5101afd4cdb65dea17d6f9312f62b66e"

# Routes
#routes = [
#  { pattern = "api.bikera.org/*", zone_name = "bikera.org" }
#]

# KV Namespaces - FIXED binding name
kv_namespaces = [
  { binding = "BikeraWorkerClaude", id = "e7d9c1a79b58413fbd07cea0714e07f2" }
]

# Durable Objects for rate limiting
[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"

[[migrations]]
tag = "v1"
new_classes = ["RateLimiter"]

# Queue for async processing
[[queues.producers]]
binding = "LOCATION_QUEUE"
queue = "location-processing"

[[queues.consumers]]
queue = "location-processing"
max_batch_size = 100
max_batch_timeout = 30

# Environment variables (public values only)
[vars]
# Replace these with your actual values
SUPABASE_URL = "https://your-project.supabase.co"
ICP_CANISTER_URL = "https://your-canister.ic0.app"
SOLANA_RPC_URL = "https://api.mainnet-beta.solana.com"
TOKEN_ADDRESS = "FtrH7NCrPDkhDmKCCdTnsDBFxiibc1X5aJPHqKQnpump"

# Pi-Node endpoints (update with your actual pi-node addresses)
PI_ENDPOINTS = '{"default":"http://pi1.bikera.org:3000","zone1":"http://pi2.bikera.org:3000"}'

# Rate limiting configuration
USER_RATE_LIMIT_WINDOW = 150000
IP_RATE_LIMIT_WINDOW = 60000
USER_RATE_LIMIT = 1
IP_RATE_LIMIT = 1000

# Batch processing configuration
MIN_BATCH_SIZE = 100
MAX_BATCH_WAIT = 300000
MAX_BATCH_SIZE = 1000

# Optional features
GEO_FENCE_ENABLED = false
DEBUG = false