[workspace]
members = [
    "validator",
    "consensus", 
    "rewards"
]
resolver = "2"

[workspace.dependencies]
candid = "0.10"
ic-cdk = "0.13"
ic-cdk-macros = "0.13"
ic-stable-structures = "0.6"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
hex = "0.4"
