[package]
name = "rewards"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = "0.10"
ic-cdk = "0.13"
ic-cdk-macros = "0.9"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
hex = "0.4"
ic-stable-structures = "0.6"

[lib]
crate-type = ["cdylib"]